os:
  - linux
before_install:
  - cat /etc/issue.net
  - whoami
  - pwd
env:
  - CXX=g++
  - CXX=clang++
before_script:
  - ./scripts/travis/before_script.sh
script:
  - ./scripts/travis/script.sh
sudo: false
