language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
osx_image: xcode61
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y autoconf bison flex llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew link --force llvm; fi
  - autoconf
