language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
osx_image: xcode61
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y build-essential autoconf automake libtool bison flex llvm-3.4 llvm-3.4-dev libedit-dev libglib2.0-0 libglib2.0-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install llvm && brew link --force llvm; fi
before_script:
  - mkdir m4 && ./autogen.sh
script:
  - ./configure CXXFLAGS='-std=c++0x' && make && make check
after_failure:
  - cat config.log
